  
 export const TODO_ADDED ="TODO_ADDED"
 export const TODO_REMOVED="TODO_REMOVED"
 export const TODO_EDITED="TODO_EDITED"
 export const TODO_COMPLETED="TODO_COMPLETED"
 export const TODO_SAVED="TODO_SAVED"
 export const TODO_DONE_FILTRED="TODO_DONE_FILTRED"
 export const TODO_NOTDONE_FILTRED="TODO_NOTDONE_FILTRED"
 export const TODOS_RESET="TODOS_RESET"